# Generated by Django 2.2 on 2019-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('LC', 'Laptops & Computers'), ('ST', 'Smartphones & Tablets'), ('G', 'Gadgets'), ('A', 'Accessories')], default='LC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('D', 'danger')], default='P', max_length=100),
            preserve_default=False,
        ),
    ]
