# Generated by Django 2.2 on 2019-06-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
