# Generated by Django 2.2 on 2019-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
    ]
