# Generated by Django 2.2 on 2019-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_item_not_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discounted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='not_discounted',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
