# Generated by Django 2.2 on 2019-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190702_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
